<?php

/**
 * Restrict type
 */
defined('RESTRICT_TYPE_IP') OR define('RESTRICT_TYPE_IP', 10);

/**
 * Limit per page
 */
defined('PER_PAGE') OR define('PER_PAGE', 20);

/**
 * Session key for account
 */
defined('SESSION_ACCOUNT_INDEX_URL') OR define('SESSION_ACCOUNT_INDEX_URL', 'SESSION_ACCOUNT_INDEX_URL');
defined('SESSION_ACCOUNT_SORT_COLUMN') OR define('SESSION_ACCOUNT_SORT_COLUMN', 'SESSION_ACCOUNT_SORT_COLUMN');
defined('SESSION_ACCOUNT_SORT_DIRECTION') OR define('SESSION_ACCOUNT_SORT_DIRECTION', 'SESSION_ACCOUNT_SORT_DIRECTION');

/**
 * Session key for organization
 */
defined('SESSION_ORGANIZATION_INDEX_URL') OR define('SESSION_ORGANIZATION_INDEX_URL', 'SESSION_ORGANIZATION_INDEX_URL');
defined('SESSION_ORGANIZATION_SORT_COLUMN') OR define('SESSION_ORGANIZATION_SORT_COLUMN', 'SESSION_ORGANIZATION_SORT_COLUMN');
defined('SESSION_ORGANIZATION_SORT_DIRECTION') OR define('SESSION_ORGANIZATION_SORT_DIRECTION', 'SESSION_ORGANIZATION_SORT_DIRECTION');

/**
 * Session key for service
 */
defined('SESSION_SERVICE_INDEX_URL') OR define('SESSION_SERVICE_INDEX_URL', 'SESSION_SERVICE_INDEX_URL');
defined('SESSION_SERVICE_SORT_COLUMN') OR define('SESSION_SERVICE_SORT_COLUMN', 'SESSION_SERVICE_COLUMN');
defined('SESSION_SERVICE_SORT_DIRECTION') OR define('SESSION_SERVICE_SORT_DIRECTION', 'SESSION_SERVICE_SORT_DIRECTION');

/**
 * Session key for admin
 */
defined('SESSION_ADMIN_INDEX_URL') OR define('SESSION_ADMIN_INDEX_URL', 'SESSION_ADMIN_INDEX_URL');
defined('SESSION_ADMIN_SORT_COLUMN') OR define('SESSION_ADMIN_SORT_COLUMN', 'SESSION_ADMIN_SORT_COLUMN');
defined('SESSION_ADMIN_SORT_DIRECTION') OR define('SESSION_ADMIN_SORT_DIRECTION', 'SESSION_ADMIN_SORT_DIRECTION');

/**
 * Date format
 */
defined('DATE_FORMAT_YMD') OR define('DATE_FORMAT_YMD', 'Ymd');
defined('DATE_FORMAT_Y_M_D') OR define('DATE_FORMAT_Y_M_D', 'Y-m-d');

/**
 * Authentication Type
 * 1: IDパスワード
 * 2: 各サービス内のアカウントID
 */
defined('AUTH_TYPE_ACCOUNT_PASSWORD') OR define('AUTH_TYPE_ACCOUNT_PASSWORD', 1);
defined('AUTH_TYPE_ACCOUNT_IN_SERVICE') OR define('AUTH_TYPE_ACCOUNT_IN_SERVICE', 2);
